package com.healthcare.shared.security;

public enum Permission {
    AUTH_REFRESH,
    AUTH_LOGOUT,
    USER_PROFILE_READ,
    USER_PROFILE_WRITE,
    DOCTOR_DIRECTORY_READ,
    DOCTOR_PROFILE_READ,
    DOCTOR_TIMESLOT_READ,
    DOCTOR_TIMESLOT_WRITE,
    APPOINTMENT_READ,
    APPOINTMENT_BOOK,
    APPOINTMENT_CANCEL,
    APPOINTMENT_RESCHEDULE,
    APPOINTMENT_CONFIRM,
    NOTIFICATION_READ
}

